static int NOTIFY_IDLE = 0;
static int APP_SWITCH_ARGENT_MODE = 1;
static int APP_SWITCH_NORMAL_MODE = 2;
static int DEVICE_PACKAGE_RECEIVED = 3;
static int DEVICE_ALERT_ARGENT = 4;
static int DEVICE_SET_ARGENT = 5;
static int DEVICE_SET_NORMAL = 6;
static int NOTIFY_ARGENT =7;

static String NOTIFY_IDLE_STRING = "NOTIFY_IDLE";
static String APP_SWITCH_ARGENT_MODE_STRING = "APP_SWITCH_ARGENT_MODE";
static String APP_SWITCH_NORMAL_MODE_STRING = "APP_SWITCH_NORMAL_MODE";
static String DEVICE_PACKAGE_RECEIVED_STRING = "DEVICE_PACKAGE_RECEIVED";
static String DEVICE_ALERT_ARGENT_STRING = "DEVICE_ALERT_ARGENT";

static int STATE_UNKNOWN_RESPONSE = 9;
static int STATE_TIMOUT_NOT_REACHED = 10;
static int STATE_CANNOT_CONNECT_SERVER = 11;
static int STATE_RECEIVED = 12;

#define CHECK_STATE_DELAY 30000
#define NETWORK_DELAY 5000